name: node.js CI
on: [push]

jobs: #<-- start the jobs encapsulation
  build: #<-- start the 'build' job encapsulation
    runs-on: ubuntu-latest
    steps: #<-- start of steps encapsulation within 'build' job
      - name: Checkout code
        uses: actions/checkout@4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npb run build
    #<-- end of steps encapsulation within 'build' job
  #<-- end of 'build' job encapsulation
  test: #<-- start the 'test' job encapsulation
    needs: build
    runs-on: ubuntu-latest
    steps: #<-- start of steps encapsulation within 'test' job
      - name: Checkout code
        uses: actions/checkout@4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
      #<-- end of steps encapsulation within 'test' job
  #<-- end of 'test' job encapsulation
#<-- end of jobs encapsulation
