name: Data Passing Workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: generate data
        run: echo "Some data generated in job1" > data.txt
      - name: upload data
        uses: actions/upload-artifact@v2
        with:
          name: data-artifact
          path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: download data
        uses: actions/download-artifact@v2
        with:
          name: data-artifact
          path: data/
      - name: use data in job2
        run: cat data/data.txt
